### ISSUE TITLE
Account Query Verifies Credential Dozens Of Times

### ISSUE THREAD

**Issue by dyoder** [dashkite/enchant#22]
Response times for account query resources are between 1-4s, I suspect because of what appears to be some kind of loop that we eventually exit but executes several dozen times. Credential verification happens in each iteration.

See request `6f07d188-cc5b-4d3c-9e85-e10ec6707dd0`.

**Comment by dyoder** [comment]
Worth noting that this is only a priority because it represents a potential DOS attack vector.

**Comment by chandrn7** [comment]
Was due to resolving the unbound rune.
